### ISSUE TITLE
SEVERE: javafx.platform is not defined. Desktop will be assumed by default.

### ISSUE THREAD

**Issue by sonica799** [gluonhq/maps#45]
I have this issue with my gluon maps. My console shows this in addition to java.io.IOException: Storage Service is not available. I have added all files, jars, etc properly. My application opens to show a map but these warnings won't go away. Please help me.

![Annotation 2020-07-10 132021](https://user-images.githubusercontent.com/68098362/87130186-20e2f980-c2b0-11ea-86d3-99a448aa0b0e.jpg)

**Comment by abhinayagarwal** [comment]
Gluon Maps has a dependency on Attach and this wasn't explicitly mention in the published pom and used to cause this issue if the dependency to Attach wasn't explicit.

This has been fixed with https://github.com/gluonhq/maps/issues/54
