### ISSUE TITLE
Missing map tile

### ISSUE THREAD

**Issue by leowhss** [gluonhq/maps#50]
Hello,

I am using Gluon Maps 2.0.0-ea+3. I noticed that the same tile always fails to load for that specific zoom level.

For that same location, it does appear in other zoom levels. This issue can be repeated everytime,

Going to OSM in the browser has no issues and the tile appears.

![missing-tile](https://user-images.githubusercontent.com/6682016/93693408-15bf0c00-fb32-11ea-850f-452e16c2f914.PNG)

Thanks,

Sean

**Comment by leowhss** [comment]
Hello,

The following code was used:

///////////////////////////////////////////////////////

public class MapJFX extends Application {

/**
     * @param args the command line arguments
     */
    public static void main(String[] args) {        
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        MapView view = new MapView();
        view.setCenter(new MapPoint(1.290270, 103.851959));        
        view.setZoom(11);
        Scene scene;
        if (Platform.isDesktop()) {            
            scene = new Scene(view, 1024, 768);
            stage.setTitle("Gluon Maps Demo");
        } else {
            BorderPane bp = new BorderPane();
            bp.setCenter(view);
            final Label label = new Label("Gluon Maps Demo");
            label.setAlignment(Pos.CENTER);
            label.setMaxWidth(Double.MAX_VALUE);
            label.setStyle("-fx-background-color: dimgrey; -fx-text-fill: white;");
            bp.setTop(label);
            Rectangle2D bounds = Screen.getPrimary().getVisualBounds();
            scene = new Scene(bp, bounds.getWidth(), bounds.getHeight());
        }
        stage.setScene(scene);
        stage.show();
    }
}

**Comment by abhinayagarwal** [comment]
I am closing this issue as this cannot be replicated with Gluon Maps 2.0.0-ea+4: 

![image](https://user-images.githubusercontent.com/3197675/126632585-8497cec5-796b-43b9-a9f4-4492fa649599.png)

If this is still an issue please feel free to re-open it.
