### ISSUE TITLE
Occasional jumps occur after zooming event ends

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/maps#9]
After a zooming event ends, releasing at the same time both fingers won't cause any unexpected movement of the map, but if one finger is released with a small delay, or if it is not released at all, there is a sudden jump from the map towards the position of that finger.
This is probably caused because the zoom position (center between two fingers) changes to the remaining finger's position, and a drag event happens moving the map from the former position to the latter.

**Comment by johanvos** [comment]
sort of. When only 1 touch point is detected, and that touch point if moving without being released, a synthetic mouseDraggedEvent is generated. We have to fix this later, by looking into removing synthesized mouseEvents (https://docs.oracle.com/javase/8/javafx/api/javafx/scene/input/MouseEvent.html#isSynthesized--)

**Comment by jperedadnr** [comment]
Ok, in the meantime I'll submit a quick fix to `MapView`.

**Comment by jperedadnr** [comment]
Fixed with PR #10
